name: AUDPUT
favicon: null
layout_spectrum: 1
typography_spectrum: 0.31566
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#a6b9fe'
    - '#ffff01'
    - '#00dd00'
    - '#893600'
  brandStrength: 1
  lightness: 0.8259792
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
